sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t chechandres/docker-react .

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react1"
  env: "Dockerreact1-env"
  bucket_name: "elasticbeanstalk-us-east-2-065326203721"
  bucket_path: "docker-react1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
